configurable redirect page
lbryio/open.lbry.com pull request #20
Opened 2019-05-23 14:58 UTC by jessopb

2019-05-23 22:08 UTC, kauffj requested changes
The code is pretty good, but I think there are some UI/UX improvements that are worth making. Will discuss in chat.

2019-05-23 22:08 UTC, kauffj commented on web/redirect.html
> +      <p>If you do not have the LBRY app, you can <a class="button--primary" href="https://lbry.io/get" rel="noopener noreferrer" target="_blank">download it here</a></p>
Please replace all instances of lbry.io with lbry.com

2019-05-23 22:08 UTC, kauffj commented on web/redirect.html
> +      if (storedDest) {
what if `storedDest` is neither `appButton` nor `webButton`?

2019-05-23 22:08 UTC, kauffj commented on web/redirect.html
> +      const appButton = document.getElementById("appButton");
(I don't care that much and I can understand if this project isn't worth linting, but there's inconsistent quotation marks here and in a variety of other places)

2019-05-23 22:08 UTC, kauffj commented on web/redirect.html
> +        !rememberBox.checked && console.log('clearing preference');
is it just cool to leave `console.log` in production now? am I a dinosaur?

2019-05-23 22:08 UTC, kauffj commented on web/redirect.html
> +        dest.innerHTML = (choice === "appButton") ? "your LBRY App" : "LBRY.tv";
"appButton" and "webButton" should be consts if we're [abiding the maxims](https://gist.github.com/lyoshenka/0a43205aa9a072b196ff87e2c689a8b9)

2019-05-29 21:06 UTC, kauffj requested changes
@NetOperatorWibby can you do one more set of small changes on this?

2019-05-29 21:06 UTC, kauffj commented on web/redirect.html
> +        <button class="button--primary" id="stopButton">
I think making this a button is a mistake. This results in 4 primary styled buttons inside of the same component. There should probably only be 1 or 2.

2019-05-29 21:06 UTC, kauffj commented on web/redirect.html
> +      <p>Don't have the LBRY app? <a class="button--primary" href="https://lbry.com/get" rel="noopener noreferrer" target="_blank">Download it here</a></p>
Please make this a text link.

2019-05-29 21:06 UTC, kauffj commented on web/redirect.html
> +        <small>Click button to stop timer</small>
A button or link that says "Stop" would not need this reminder text

2019-05-29 21:06 UTC, kauffj commented on web/redirect.html
> +      <p>Don't have the LBRY app? <a class="button--primary" href="https://lbry.com/get" rel="noopener noreferrer" target="_blank">Download it here</a></p>
And can this be `meta` or `help` or something smaller than typical `<p>`?

2019-05-29 21:16 UTC, NetOpWibby commented on web/redirect.html
> +        <small>Click button to stop timer</small>
Why is this text bad? What would a better interface look like?

2019-05-29 21:17 UTC, kauffj commented on web/redirect.html
> +        <small>Click button to stop timer</small>
If there's a button and/or link that says stop, then you do not need hint text to tell me what to do.

2019-05-30 15:13 UTC, merged