Request to Update Webredirect
lbryio/open.lbry.com pull request #8
Opened 2018-05-19 18:36 UTC by fabianosantosnet

Hi. I made some updates in the project:
- create files: interactions.js and style.css;
- update code: index.php and homepage.html;
- improve the page style homepage.html.

I guess that are some issues that we have to do like internationalization. I suggest that the file homepage.html should be php file not html.

2018-05-21 22:37 UTC, kauffj commented
Thank you @fabianosantosnet !

I've asked @nikooo777 to review.

We'd also be happy to send you some LBC as thanks, please see [this article](https://lbry.io/faq/tips).

I'm for internationalization, but I'm not sure the right way to do this is to put both on the same page.

Maybe you could create two different landing pages, one in Spanish and one in English?

2018-05-23 10:52 UTC, nikooo777 requested changes
Thank you, the refactor is good. If you fix those 3 lines I'll proceed with merging :)

2018-05-23 10:52 UTC, nikooo777 commented on web/homepage.html
> +  <title>Open in LBRY &sol; Abrir em LBRY</title>
Yes I would suggest we don't mix 2 languages on the same page. Could you change this one back to English only?

2018-05-23 10:52 UTC, nikooo777 commented on web/homepage.html
> +  <h1>Open with LBRY / Abrir em LBRY</h1>
Same here

2018-05-23 10:52 UTC, nikooo777 commented on web/homepage.html
> +    <input type="text" id="name" placeholder="Search &sol; Buscar" />
and here

2018-05-23 21:16 UTC, fabianosantosnet commented
Hi. I made the changes.

2018-05-23 22:58 UTC, nikooo777 approved these changes

2018-05-23 23:01 UTC, nikooo777 commented
Thank you @fabianosantosnet!
As @kauffj don't hesitate to take a look at the article above, maybe join us on discord so we can offer you a tip for your help :)

2018-05-23 23:01 UTC, merged

2018-05-31 13:11 UTC, tzarebczan commented
@nikooo777 the prompt where you enter URIs now says "search" - it should say something along the lines of "Enter LBRY Claim / Channel here". Also, before it used to show that the lbry:// is prepended, now it's not clear (unless they look at the resulting URL)