Things updated
lbryio/open.lbry.com pull request #9
Opened 2018-05-31 15:26 UTC by fabianosantosnet

See updated made:
web/style.css -> added some css and organize some. let wlink hidden. improve style.
web/homepage.html -> added lbry protocol before input text. changed placeholder info according to @tzarebczan comment.
web/interactions.js -> added wlink element to display onkeypress. removed encoding url to textContent.

2018-06-01 00:53 UTC, nikooo777 commented
I actually changed the search field myself (as you can see from the last commit) so this is why there is a conflict right now. Can you either remove that change from your branch or rebase?
Thanks a lot for the prompt PR here!

2018-06-01 00:54 UTC, nikooo777 commented on web/homepage.html
> +    <span>lbry://</span><input type="text" id="name" placeholder="Enter LBRY Claim / Channel here" maxlength="100" />
i changed the placeholder too in my last commit so you should rebase or anyway merge my changes in your branch to avoid the conflict

2018-06-01 00:55 UTC, nikooo777 requested changes
see comment

2018-06-01 01:20 UTC, nikooo777 commented
now you lost the span everything else though. I think your version was superior to mine, but because we both edited the same line it wouldn't allow for merging without a rebase or something. see if you can bring those back and make this merge-able

2018-06-01 01:58 UTC, fabianosantosnet commented
Removed conflict

2018-06-06 17:16 UTC, nikooo777 approved these changes

2018-06-06 17:17 UTC, merged